name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: Niklas-dev/buildozer-action@v1.2
        with:
          command: buildozer android debug
          buildozer_version: stable
